# Makefile for solve library
#
# Author: Alex Hamel, James Verschleiser, Jordan Sanz
# Date: 08/19/2020
# Class: CS50
# Professor: Xia Zhou

# Dependencies: object files depend on header files
solve.o: solve.h ../common/puzzle.h

.PHONY: clean

# clean up after our compilation
clean:
	rm -f core
	rm -rf *.dSYM
	rm -f *~ *.o
